# ๐๐ธ๐ญ๐ฎ๐ญ ๐ซ๐ ๐๐๐ธ๐ผ๐ถ๐ฒ๐พ๐ถ (vk.com/prodbyhakin)
# ะะฐัะฟะพัััะฐะฝะตะฝะธะต ะฟัะพะดัะบัะฐ ัะฐะทัะตัะตะฝะพ ัะพะปัะบะพ ะฟะพ
# ะฟัะตะดะฒะฐัะธัะตะปัะฝะพะผั ัะพะณะปะฐัะธั ั ะฐะฒัะพัะพะผ.

Settings:
  server-name: "lobby"
  # ะะตะถะธะผ ัะฐะฑะพัั ะฟะปะฐะณะธะฝะฐ:
  # 0 - ัะฐะผะพััะพััะตะปัะฝัะน
  # 1 - ั ะฟัะพะบัะธ-ัะตัะฒะตัะพะผ
  mode: 1